spring:
  application:
    name: timetracker
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/timetrackerdb;AUTO_SERVER=TRUE
    username: root
    password: password
    driverClassName: org.h2.Driver
    #url: jdbc:h2:file:./src/main/resources/data/timetrackerdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    #url: jdbc:h2:mem:mydb # alternative: url: jdbc:h2:file:/data/demo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    #prefix: src/main/resources/templates/ #classpath:/templates/
    enabled: true